import fs from 'node:fs/promises';
import path from 'node:path';
import { paths } from './config.mjs';
import { SELF_ID } from './changelog.mjs';
import { dim } from './log.mjs';

/**
 * Turns the collected history into pages, so a changelog stays readable once
 * there is real history behind it:
 *
 *   Changelog
 *   |- FeastDocs            <- one category per repository
 *   |  \- 2026              <- one category per year
 *   |     |- August         <- one page per month
 *   |     \- July
 *   \- Checkout API
 *      \- 2026
 *         \- August
 *
 * The repository level is dropped when `groupByRepo` is off, or when it is
 * 'auto' and there is only one source.
 *
 * These are ordinary Markdown files, so the sidebar, search, prev/next links,
 * prerendering and the sitemap treat them like any other page — no special
 * cases anywhere else in the pipeline. Each file carries only a filter
 * (`<fd-changelog repo="…" month="2026-08">`) and never the commits, so a new
 * commit changes no file and a new month adds one.
 */
const MARKER = '<!-- AUTO-GENERATED by `npm run docs:build` — edits are overwritten. -->';

const MONTHS = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export async function writeChangelogPages(config, changelog) {
  const { monthlyPages, monthlyPagesDir, groupByRepo } = config.changelog;
  if (!monthlyPages) return;

  const root = path.join(paths.docs(config), monthlyPagesDir);

  // Every source in a stable order: this repository first, then the configured
  // ones as listed. A source with no commits contributes no pages.
  const datasets = [
    { id: SELF_ID, ...changelog.sources[SELF_ID], commits: changelog.commits },
    ...Object.entries(changelog.byRepo).map(([id, commits]) => ({
      id,
      ...changelog.sources[id],
      commits,
    })),
  ].filter((dataset) => dataset.commits.length > 0);

  if (datasets.length === 0) return;

  const grouped = groupByRepo === 'auto' ? datasets.length > 1 : Boolean(groupByRepo);
  const expected = new Set();
  let written = 0;

  for (const [order, dataset] of datasets.entries()) {
    const base = grouped ? path.join(root, dataset.slug) : root;

    if (grouped) {
      await fs.mkdir(base, { recursive: true });

      // An index inside a category folder becomes that category's own link, so
      // this is where a repository's months belong — the section index stays a
      // way in, not a second copy of every listing.
      const indexFile = path.join(base, 'index.md');
      expected.add(indexFile);
      if (await writeIfChanged(indexFile, repoIndexPage(dataset))) written += 1;

      // Config order decides sidebar order, so readers see the products in the
      // order the site owner listed them.
      written += await writeCategory(base, expected, {
        label: dataset.title,
        // After any hand-written page in the section, in config order.
        position: 1000 + order,
      });
    }

    for (const [year, months] of groupByYear(dataset.commits)) {
      const yearDir = path.join(base, year);
      await fs.mkdir(yearDir, { recursive: true });

      // Newest year first, but after any hand-written page in the folder: a
      // large base keeps years below ordinary positions, and subtracting the
      // year keeps them descending among themselves.
      written += await writeCategory(yearDir, expected, {
        label: year,
        position: 10_000 - Number(year),
      });

      for (const [month, count] of months) {
        const name = MONTHS[Number(month.slice(5, 7)) - 1];
        const file = path.join(yearDir, `${name.toLowerCase()}.md`);
        expected.add(file);
        const page = monthPage({
          name,
          year,
          month,
          count,
          repo: dataset.id === SELF_ID ? null : dataset.id,
          product: grouped ? dataset.title : null,
        });
        if (await writeIfChanged(file, page)) written += 1;
      }
    }
  }

  const pruned = await pruneGenerated(root, expected, grouped);
  if (written > 0 || pruned > 0) {
    console.log(
      `  ${dim(`changelog pages: ${written} written, ${pruned} removed → ${path.relative(paths.root, root)}`)}`,
    );
  }
}

async function writeCategory(dir, expected, { label, position }) {
  const file = path.join(dir, '_category.json');
  expected.add(file);
  // `generated` marks it as ours to prune later; the pipeline reads only label
  // and position, so the extra key is inert.
  const contents = `${JSON.stringify({ label, position, generated: true }, null, 2)}\n`;
  return (await writeIfChanged(file, contents)) ? 1 : 0;
}

function repoIndexPage(dataset) {
  const total = dataset.commits.length;
  const attribute = ` repo="${dataset.id}"`;
  return (
    `---
` +
    `title: "${dataset.title.replace(/"/g, '')}"
` +
    `sidebar_label: 'Overview'
` +
    `description: '${total} change${total === 1 ? '' : 's'} recorded for ${dataset.title}.'
` +
    `---

` +
    `${MARKER}

` +
    `<fd-changelog-months${attribute}></fd-changelog-months>

` +
    `## The most recent changes

` +
    `<fd-changelog${attribute} limit="5"></fd-changelog>
`
  );
}

function monthPage({ name, year, month, count, repo, product }) {
  const attributes = repo === null ? '' : ` repo="${repo}"`;
  const heading = product === null ? `${name} ${year}` : `${product} — ${name} ${year}`;
  const scope = product === null ? '' : `${product}, `;
  return (
    `---\n` +
    `title: "${heading.replace(/"/g, '')}"\n` +
    `sidebar_label: '${name}'\n` +
    `description: '${count} change${count === 1 ? '' : 's'} in ${scope}${name} ${year}.'\n` +
    // Newest month first within the year.
    `sidebar_position: ${-Number(month.slice(5, 7))}\n` +
    `---\n\n` +
    // No body heading: the page template renders the front-matter title, and a
    // heading after the marker comment is not stripped, so it would show twice.
    `${MARKER}\n\n` +
    `<fd-changelog${attributes} month="${month}"></fd-changelog>\n`
  );
}

/** Commits per 'YYYY-MM', keyed by year — newest first, empty months skipped. */
function groupByYear(commits) {
  const counts = new Map();
  for (const commit of commits) {
    // Slice the ISO string rather than parsing it: a Date would reinterpret the
    // commit's own offset in the build machine's timezone and could move a
    // commit into a neighbouring month. The components slice it the same way.
    const month = String(commit.date).slice(0, 7);
    if (!/^\d{4}-\d{2}$/.test(month)) continue;
    counts.set(month, (counts.get(month) ?? 0) + 1);
  }

  const byYear = new Map();
  for (const month of [...counts.keys()].sort().reverse()) {
    const year = month.slice(0, 4);
    if (!byYear.has(year)) byYear.set(year, []);
    byYear.get(year).push([month, counts.get(month)]);
  }
  return byYear;
}

/**
 * Removes pages this build did not produce — a lowered `limit`, a renamed
 * product or a repository dropped from the config would otherwise leave
 * orphans behind. Only generated files are touched: month pages are matched by
 * their marker comment and categories by their `generated` flag, so anything
 * hand-written in these folders survives.
 */
async function pruneGenerated(root, expected, grouped) {
  let pruned = 0;

  // With grouping on, generated content sits one level deeper.
  const scopes = grouped ? await subdirectories(root) : [root];
  for (const scope of scopes) {
    for (const yearDir of await subdirectories(scope, /^\d{4}$/)) {
      pruned += await pruneDir(yearDir, expected);
      await removeIfEmpty(yearDir);
    }
    if (scope !== root) {
      pruned += await pruneDir(scope, expected);
      await removeIfEmpty(scope);
    }
  }

  return pruned;
}

async function pruneDir(dir, expected) {
  let pruned = 0;
  for (const file of await fs.readdir(dir).catch(() => [])) {
    const full = path.join(dir, file);
    if (expected.has(full)) continue;

    if (file === '_category.json') {
      const raw = await fs.readFile(full, 'utf8').catch(() => '');
      let parsed = {};
      try {
        parsed = JSON.parse(raw || '{}');
      } catch {
        continue; // Malformed, and not ours to delete.
      }
      if (!parsed.generated) continue;
    } else if (file.endsWith('.md')) {
      const contents = await fs.readFile(full, 'utf8').catch(() => '');
      if (!contents.includes(MARKER)) continue;
    } else {
      continue;
    }

    await fs.rm(full, { force: true });
    pruned += 1;
  }
  return pruned;
}

async function subdirectories(dir, pattern = null) {
  const entries = await fs.readdir(dir, { withFileTypes: true }).catch(() => []);
  return entries
    .filter((entry) => entry.isDirectory() && (pattern === null || pattern.test(entry.name)))
    .map((entry) => path.join(dir, entry.name));
}

/** An empty folder would render as an empty category. */
async function removeIfEmpty(dir) {
  const left = await fs.readdir(dir).catch(() => ['keep']);
  if (left.length === 0) await fs.rmdir(dir).catch(() => {});
}

/** Returns true when the file was actually written. */
async function writeIfChanged(file, contents) {
  const existing = await fs.readFile(file, 'utf8').catch(() => null);
  if (existing === contents) return false;
  await fs.writeFile(file, contents, 'utf8');
  return true;
}
