import fs from 'node:fs/promises';
import path from 'node:path';
import { paths } from './config.mjs';

const BANNER = `// AUTO-GENERATED by \`npm run docs:build\` — do not edit.\n// Source of truth: the docs/ folder and feastdocs.config.mjs.\n`;

export async function emit({ config, docs, sections, assets, changelog, versions }) {
  await fs.mkdir(paths.generatedDocs, { recursive: true });

  const used = new Set();
  const modules = docs.map((doc) => {
    let file = moduleName(doc.slug);
    // Two different slugs can sanitise to the same filename; keep them apart.
    while (used.has(file)) file += '_';
    used.add(file);
    return { doc, file };
  });

  await Promise.all([
    writeDocModules(modules),
    writeRegistry(modules, sections, versions),
    writeSiteConfig(config),
    writeSearchIndex(docs, sections),
    writeChangelog(changelog),
    syncAssets(config, assets),
  ]);

  await pruneStaleModules(new Set(modules.map((m) => `${m.file}.ts`)));
}

async function writeDocModules(modules) {
  await Promise.all(
    modules.map(({ doc, file }) => {
      const payload = {
        slug: doc.slug,
        section: doc.section,
        title: doc.title,
        description: doc.description,
        sourcePath: doc.sourcePath,
        lastUpdated: doc.lastUpdated,
        lastAuthor: doc.lastAuthor,
        showToc: doc.showToc,
        showSidebar: doc.showSidebar,
        tags: doc.tags,
        headings: doc.headings,
        prev: doc.prev,
        next: doc.next,
        css: doc.css,
        html: doc.html,
      };
      const contents = `${BANNER}\nexport default ${JSON.stringify(payload, null, 2)};\n`;
      return writeIfChanged(path.join(paths.generatedDocs, `${file}.ts`), contents);
    }),
  );
}

async function writeRegistry(modules, sections, versions = []) {
  const index = modules.map(({ doc }) => ({
    slug: doc.slug,
    section: doc.section,
    title: doc.title,
    sidebarLabel: doc.sidebarLabel,
    description: doc.description,
  }));

  const loaders = modules
    .map(({ doc, file }) => `  ${JSON.stringify(doc.slug)}: () => import('./docs/${file}'),`)
    .join('\n');

  const contents =
    `${BANNER}\n` +
    `import type { DocContent, DocSection, DocSummary, DocVersion } from '../core/models';\n\n` +
    `/** Every page, lazily loaded so each document ships as its own chunk. */\n` +
    `export const DOC_LOADERS: Record<string, () => Promise<{ default: DocContent }>> = {\n${loaders}\n};\n\n` +
    `/** Lightweight metadata for all pages — safe to keep in the initial bundle. */\n` +
    `export const DOC_INDEX: readonly DocSummary[] = ${JSON.stringify(index, null, 2)};\n\n` +
    `/** Top-level sections, each with its own sidebar tree. */\n` +
    `export const SECTIONS: readonly DocSection[] = ${JSON.stringify(sections, null, 2)};\n\n` +
    `/**\n` +
    ` * Source paths in sidebar order. The content manager sorts its file tree\n` +
    ` * by this, so what an author drags matches what a reader sees.\n` +
    ` */\n` +
    `export const PAGE_ORDER: readonly string[] = ${JSON.stringify(pageOrder(modules, sections), null, 2)};\n\n` +
    `/**\n` +
    ` * Documented versions, newest first. A single entry with an empty id means\n` +
    ` * the site is not versioned, which is the common case.\n` +
    ` */\n` +
    `export const VERSIONS: readonly DocVersion[] = ${JSON.stringify(versions, null, 2)};\n`;

  await writeIfChanged(path.join(paths.generated, 'registry.ts'), contents);
}

/** Flattens the section trees into source paths, in the order readers see. */
function pageOrder(modules, sections) {
  const bySlug = new Map(modules.map(({ doc }) => [doc.slug, doc.sourcePath]));
  const out = [];
  const walk = (items) => {
    for (const item of items) {
      if (item.type === 'doc') {
        const source = bySlug.get(item.slug);
        if (source) out.push(source);
        continue;
      }
      if (item.slug != null) {
        const source = bySlug.get(item.slug);
        if (source) out.push(source);
      }
      walk(item.items);
    }
  };
  for (const section of sections) walk(section.items);
  return out;
}

/**
 * Repository history for the <fd-changelog> component. Kept in its own module
 * so it is a lazy chunk: the initial bundle never carries it.
 */
async function writeChangelog({ commits, byRepo, sources }) {
  const contents =
    `${BANNER}
` +
    `import type { ChangelogEntry, ChangelogSource } from '../core/models';

` +
    `export const CHANGELOG: readonly ChangelogEntry[] = ${JSON.stringify(commits, null, 2)};

` +
    `/** Keyed by source id — 'owner/name', 'azure:org/project/repo', or an explicit id. */
` +
    `export const CHANGELOG_BY_REPO: Readonly<Record<string, readonly ChangelogEntry[]>> = ${JSON.stringify(byRepo, null, 2)};

` +
    `/** Where each source's commits can be viewed, so links work per host. */
` +
    `export const CHANGELOG_SOURCES: Readonly<Record<string, ChangelogSource>> = ${JSON.stringify(sources, null, 2)};
`;
  await writeIfChanged(path.join(paths.generated, 'changelog.ts'), contents);
}

async function writeSiteConfig(config) {
  const payload = {
    title: config.title,
    tagline: config.tagline,
    docsDir: config.docsDir,
    logo: config.logo,
    navbar: config.navbar,
    footer: config.footer,
    theme: config.theme,
    sidebar: config.sidebar,
    editUrl: config.editUrl,
    showLastUpdated: config.showLastUpdated,
    github: config.github,
    sourceRepo: config.sourceRepo,
    sourceLabel: config.sourceLabel,
    editor: config.editor,
    changelog: {
      monthlyPages: config.changelog.monthlyPages,
      monthlyPagesDir: config.changelog.monthlyPagesDir,
      groupByRepo: config.changelog.groupByRepo,
    },
  };
  const contents =
    `${BANNER}\n` +
    `import type { SiteConfig } from '../core/models';\n\n` +
    `export const SITE: SiteConfig = ${JSON.stringify(payload, null, 2)};\n`;
  await writeIfChanged(path.join(paths.generated, 'site-config.ts'), contents);
}

/**
 * The search index is split per heading section so a hit can deep-link straight
 * to the relevant anchor instead of dumping the reader at the top of the page.
 */
async function writeSearchIndex(docs, sections) {
  const sectionLabels = new Map(sections.map((section) => [section.id, section.label]));
  const records = [];

  for (const doc of docs) {
    const sectionLabel = doc.section === null ? '' : (sectionLabels.get(doc.section) ?? '');
    for (const part of splitSections(doc)) {
      if (!part.text && !part.heading) continue;
      records.push({
        version: doc.version ?? '',
        slug: doc.slug,
        section: sectionLabel,
        page: doc.title,
        anchor: part.id,
        heading: part.heading,
        text: part.text.slice(0, 1200),
      });
    }
  }

  await fs.mkdir(paths.public, { recursive: true });
  await writeIfChanged(path.join(paths.public, 'search-index.json'), JSON.stringify(records));
}

function splitSections(doc) {
  const html = doc.html;
  const headingPattern = /<h([23])\b[^>]*\bid="([^"]+)"[^>]*>([\s\S]*?)<\/h\1>/gi;
  const parts = [];
  let cursor = 0;
  let current = { id: '', heading: '', text: '' };

  for (const match of html.matchAll(headingPattern)) {
    current.text = toPlainText(html.slice(cursor, match.index));
    parts.push(current);
    current = { id: match[2], heading: toPlainText(match[3]), text: '' };
    cursor = match.index + match[0].length;
  }
  current.text = toPlainText(html.slice(cursor));
  parts.push(current);

  // The lead part carries the page title and description so a page is findable
  // even before its first subheading.
  parts[0].heading = doc.title;
  parts[0].text = [doc.description, parts[0].text].filter(Boolean).join(' ');
  return parts;
}

function toPlainText(html) {
  return html
    .replace(/<a\b[^>]*class="[^"]*fd-heading-anchor[^"]*"[^>]*>[\s\S]*?<\/a>/gi, '')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&(?:amp|lt|gt|quot|#39|nbsp);/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/** Copies everything that isn't a doc or a stylesheet into public/docs-assets. */
async function syncAssets(config, assets) {
  const docsRoot = paths.docs(config);
  const target = paths.publicAssets;
  await fs.mkdir(target, { recursive: true });

  const keep = new Set(assets);
  for (const relative of assets) {
    const from = path.join(docsRoot, relative);
    const to = path.join(target, relative);
    await fs.mkdir(path.dirname(to), { recursive: true });

    const [source, existing] = await Promise.all([fs.stat(from), fs.stat(to).catch(() => null)]);
    // Skip untouched files: rewriting them would retrigger the dev server.
    if (existing && existing.size === source.size && existing.mtimeMs >= source.mtimeMs) continue;
    await fs.copyFile(from, to);
  }

  await pruneMissing(target, target, keep);
}

async function pruneMissing(dir, root, keep) {
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      await pruneMissing(full, root, keep);
      const remaining = await fs.readdir(full);
      if (remaining.length === 0) await fs.rmdir(full);
    } else {
      const relative = path.relative(root, full).split(path.sep).join('/');
      if (!keep.has(relative)) await fs.rm(full);
    }
  }
}

async function pruneStaleModules(expected) {
  const entries = await fs.readdir(paths.generatedDocs).catch(() => []);
  await Promise.all(
    entries
      .filter((name) => name.endsWith('.ts') && !expected.has(name))
      .map((name) => fs.rm(path.join(paths.generatedDocs, name))),
  );
}

/** Avoids touching files whose content is identical, keeping dev rebuilds quiet. */
async function writeIfChanged(file, contents) {
  const current = await fs.readFile(file, 'utf8').catch(() => null);
  if (current === contents) return false;
  await fs.writeFile(file, contents, 'utf8');
  return true;
}

function moduleName(slug) {
  if (slug === '') return '_home';
  return slug.replace(/[^a-zA-Z0-9._-]+/g, '--').replace(/^-+|-+$/g, '') || '_page';
}
